### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by jsejcksn**
This needs to be tested. It is intended to address the following security advisories:

- https://github.com/advisories/GHSA-5fw9-fq32-wv5p via https://github.com/js-hackers/weather-api/security/dependabot/package-lock.json/node-notifier/open

### CODE REVIEW

**Comment by jsejcksn** [comment]
@samueldlay I'm only seeing `500` status codes on all responses (which means it's throwing internally). It could simply be an issue with the API key.

We should either investigate and fix, or retire this project. What do you think?

**Comment by samueldlay** [comment]
We should investigate, but I have a lot going on during this work week. I am free Saturday and Sunday mid morning/early afternoon.

**Comment by jsejcksn** [comment]
@samueldlay Ok—if you want to coordinate a time to work synchronously, we can do that privately outside of GitHub.

**Comment by jsejcksn** [comment]
@samueldlay I took a look at this:

From the stack trace, it appears that it throws while fetching a location when none is provided (line 12):

https://github.com/js-hackers/weather-api/blob/06a52e8c962989ca89da61b7f94151b5c689a877/api/_utils/location-api.ts#L8-L28

If a location is provided via a query parameter, everything works correctly. Since the issue is not related to upgrading the dependencies, I'll go ahead and merge this PR, and I'll open a new issue about that API.

**Pull request merged**
